version: '3.8'
services:
  spring-boot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3308/order_it
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kwak8174
      SPRING_PROFILES_ACTIVE: dev  # 환경 변수 추가

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kwak8174
      MYSQL_DATABASE: order_it
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
