spring:
  # DB Setting
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: 'jdbc:mariadb://localhost:3306/order_it'
    username: root
    password: kwak8174

  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

  # Image Validation
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Spring DOC
springdoc:
  packages-to-scan: 'inu.amigo.order_it.item, inu.amigo.order_it.order'
  swagger-ui:
    operations-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true

# Image Path
image:
  path: /home/ubuntu/img/

# Server Image Path : /home/ubuntu/img/
# Local Image Path : /Users/kbm/Documents/Study/order_it/src/main/resources/static/img/

