name: CI/CD for order_it Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Transfer JAR to EC2
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/deploy"

      - name: Transfer Deploy Script use SCP
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy.sh"
          target: "/home/ubuntu/deploy"

      - name: Execute JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: chmod +x /home/ubuntu/deploy/deploy.sh && sudo sh /home/ubuntu/deploy/deploy.sh